// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/auth.dart';
import 'api/calls.dart';
import 'api/teams.dart';
import 'api/trouter.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  RustStreamSink<CallEvent> dco_decode_StreamSink_call_event_Sse(dynamic raw);

  @protected
  RustStreamSink<MessageEvent> dco_decode_StreamSink_message_event_Sse(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AuthStatus dco_decode_auth_status(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  CustomReaction dco_decode_box_autoadd_custom_reaction(dynamic raw);

  @protected
  MessageImage dco_decode_box_autoadd_message_image(dynamic raw);

  @protected
  RemoteVideoFrame dco_decode_box_autoadd_remote_video_frame(dynamic raw);

  @protected
  SavedAccountNotification dco_decode_box_autoadd_saved_account_notification(
    dynamic raw,
  );

  @protected
  CallEvent dco_decode_call_event(dynamic raw);

  @protected
  Channel dco_decode_channel(dynamic raw);

  @protected
  Chat dco_decode_chat(dynamic raw);

  @protected
  CustomReaction dco_decode_custom_reaction(dynamic raw);

  @protected
  DeviceCode dco_decode_device_code(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<Channel> dco_decode_list_channel(dynamic raw);

  @protected
  List<Chat> dco_decode_list_chat(dynamic raw);

  @protected
  List<MediaDeviceInfo> dco_decode_list_media_device_info(dynamic raw);

  @protected
  List<Message> dco_decode_list_message(dynamic raw);

  @protected
  List<MessageImage> dco_decode_list_message_image(dynamic raw);

  @protected
  List<MessageQuote> dco_decode_list_message_quote(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<Reaction> dco_decode_list_reaction(dynamic raw);

  @protected
  List<ReactionUser> dco_decode_list_reaction_user(dynamic raw);

  @protected
  List<SavedAccount> dco_decode_list_saved_account(dynamic raw);

  @protected
  List<SavedAccountConversation> dco_decode_list_saved_account_conversation(
    dynamic raw,
  );

  @protected
  List<Team> dco_decode_list_team(dynamic raw);

  @protected
  List<UserPresence> dco_decode_list_user_presence(dynamic raw);

  @protected
  MediaDeviceInfo dco_decode_media_device_info(dynamic raw);

  @protected
  Message dco_decode_message(dynamic raw);

  @protected
  MessageEvent dco_decode_message_event(dynamic raw);

  @protected
  MessageImage dco_decode_message_image(dynamic raw);

  @protected
  MessageQuote dco_decode_message_quote(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  CustomReaction? dco_decode_opt_box_autoadd_custom_reaction(dynamic raw);

  @protected
  MessageImage? dco_decode_opt_box_autoadd_message_image(dynamic raw);

  @protected
  RemoteVideoFrame? dco_decode_opt_box_autoadd_remote_video_frame(dynamic raw);

  @protected
  SavedAccountNotification?
  dco_decode_opt_box_autoadd_saved_account_notification(dynamic raw);

  @protected
  Reaction dco_decode_reaction(dynamic raw);

  @protected
  ReactionUser dco_decode_reaction_user(dynamic raw);

  @protected
  RemoteVideoFrame dco_decode_remote_video_frame(dynamic raw);

  @protected
  SavedAccount dco_decode_saved_account(dynamic raw);

  @protected
  SavedAccountConversation dco_decode_saved_account_conversation(dynamic raw);

  @protected
  SavedAccountNotification dco_decode_saved_account_notification(dynamic raw);

  @protected
  Team dco_decode_team(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  UserDetails dco_decode_user_details(dynamic raw);

  @protected
  UserPresence dco_decode_user_presence(dynamic raw);

  @protected
  UserProfile dco_decode_user_profile(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  RustStreamSink<CallEvent> sse_decode_StreamSink_call_event_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<MessageEvent> sse_decode_StreamSink_message_event_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AuthStatus sse_decode_auth_status(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  CustomReaction sse_decode_box_autoadd_custom_reaction(
    SseDeserializer deserializer,
  );

  @protected
  MessageImage sse_decode_box_autoadd_message_image(
    SseDeserializer deserializer,
  );

  @protected
  RemoteVideoFrame sse_decode_box_autoadd_remote_video_frame(
    SseDeserializer deserializer,
  );

  @protected
  SavedAccountNotification sse_decode_box_autoadd_saved_account_notification(
    SseDeserializer deserializer,
  );

  @protected
  CallEvent sse_decode_call_event(SseDeserializer deserializer);

  @protected
  Channel sse_decode_channel(SseDeserializer deserializer);

  @protected
  Chat sse_decode_chat(SseDeserializer deserializer);

  @protected
  CustomReaction sse_decode_custom_reaction(SseDeserializer deserializer);

  @protected
  DeviceCode sse_decode_device_code(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<Channel> sse_decode_list_channel(SseDeserializer deserializer);

  @protected
  List<Chat> sse_decode_list_chat(SseDeserializer deserializer);

  @protected
  List<MediaDeviceInfo> sse_decode_list_media_device_info(
    SseDeserializer deserializer,
  );

  @protected
  List<Message> sse_decode_list_message(SseDeserializer deserializer);

  @protected
  List<MessageImage> sse_decode_list_message_image(
    SseDeserializer deserializer,
  );

  @protected
  List<MessageQuote> sse_decode_list_message_quote(
    SseDeserializer deserializer,
  );

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<Reaction> sse_decode_list_reaction(SseDeserializer deserializer);

  @protected
  List<ReactionUser> sse_decode_list_reaction_user(
    SseDeserializer deserializer,
  );

  @protected
  List<SavedAccount> sse_decode_list_saved_account(
    SseDeserializer deserializer,
  );

  @protected
  List<SavedAccountConversation> sse_decode_list_saved_account_conversation(
    SseDeserializer deserializer,
  );

  @protected
  List<Team> sse_decode_list_team(SseDeserializer deserializer);

  @protected
  List<UserPresence> sse_decode_list_user_presence(
    SseDeserializer deserializer,
  );

  @protected
  MediaDeviceInfo sse_decode_media_device_info(SseDeserializer deserializer);

  @protected
  Message sse_decode_message(SseDeserializer deserializer);

  @protected
  MessageEvent sse_decode_message_event(SseDeserializer deserializer);

  @protected
  MessageImage sse_decode_message_image(SseDeserializer deserializer);

  @protected
  MessageQuote sse_decode_message_quote(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  CustomReaction? sse_decode_opt_box_autoadd_custom_reaction(
    SseDeserializer deserializer,
  );

  @protected
  MessageImage? sse_decode_opt_box_autoadd_message_image(
    SseDeserializer deserializer,
  );

  @protected
  RemoteVideoFrame? sse_decode_opt_box_autoadd_remote_video_frame(
    SseDeserializer deserializer,
  );

  @protected
  SavedAccountNotification?
  sse_decode_opt_box_autoadd_saved_account_notification(
    SseDeserializer deserializer,
  );

  @protected
  Reaction sse_decode_reaction(SseDeserializer deserializer);

  @protected
  ReactionUser sse_decode_reaction_user(SseDeserializer deserializer);

  @protected
  RemoteVideoFrame sse_decode_remote_video_frame(SseDeserializer deserializer);

  @protected
  SavedAccount sse_decode_saved_account(SseDeserializer deserializer);

  @protected
  SavedAccountConversation sse_decode_saved_account_conversation(
    SseDeserializer deserializer,
  );

  @protected
  SavedAccountNotification sse_decode_saved_account_notification(
    SseDeserializer deserializer,
  );

  @protected
  Team sse_decode_team(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  UserDetails sse_decode_user_details(SseDeserializer deserializer);

  @protected
  UserPresence sse_decode_user_presence(SseDeserializer deserializer);

  @protected
  UserProfile sse_decode_user_profile(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_call_event_Sse(
    RustStreamSink<CallEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_message_event_Sse(
    RustStreamSink<MessageEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_auth_status(AuthStatus self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_custom_reaction(
    CustomReaction self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_message_image(
    MessageImage self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_remote_video_frame(
    RemoteVideoFrame self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_saved_account_notification(
    SavedAccountNotification self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_call_event(CallEvent self, SseSerializer serializer);

  @protected
  void sse_encode_channel(Channel self, SseSerializer serializer);

  @protected
  void sse_encode_chat(Chat self, SseSerializer serializer);

  @protected
  void sse_encode_custom_reaction(
    CustomReaction self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_device_code(DeviceCode self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_channel(List<Channel> self, SseSerializer serializer);

  @protected
  void sse_encode_list_chat(List<Chat> self, SseSerializer serializer);

  @protected
  void sse_encode_list_media_device_info(
    List<MediaDeviceInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_message(List<Message> self, SseSerializer serializer);

  @protected
  void sse_encode_list_message_image(
    List<MessageImage> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_message_quote(
    List<MessageQuote> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_reaction(List<Reaction> self, SseSerializer serializer);

  @protected
  void sse_encode_list_reaction_user(
    List<ReactionUser> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_saved_account(
    List<SavedAccount> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_saved_account_conversation(
    List<SavedAccountConversation> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_team(List<Team> self, SseSerializer serializer);

  @protected
  void sse_encode_list_user_presence(
    List<UserPresence> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_media_device_info(
    MediaDeviceInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_message(Message self, SseSerializer serializer);

  @protected
  void sse_encode_message_event(MessageEvent self, SseSerializer serializer);

  @protected
  void sse_encode_message_image(MessageImage self, SseSerializer serializer);

  @protected
  void sse_encode_message_quote(MessageQuote self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_custom_reaction(
    CustomReaction? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_message_image(
    MessageImage? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_remote_video_frame(
    RemoteVideoFrame? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_saved_account_notification(
    SavedAccountNotification? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_reaction(Reaction self, SseSerializer serializer);

  @protected
  void sse_encode_reaction_user(ReactionUser self, SseSerializer serializer);

  @protected
  void sse_encode_remote_video_frame(
    RemoteVideoFrame self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_saved_account(SavedAccount self, SseSerializer serializer);

  @protected
  void sse_encode_saved_account_conversation(
    SavedAccountConversation self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_saved_account_notification(
    SavedAccountNotification self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_team(Team self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_user_details(UserDetails self, SseSerializer serializer);

  @protected
  void sse_encode_user_presence(UserPresence self, SseSerializer serializer);

  @protected
  void sse_encode_user_profile(UserProfile self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;
}
