// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `service`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `from`, `from`, `from`

Future<AuthStatus> getAuthStatus() =>
    RustLib.instance.api.crateApiAuthGetAuthStatus();

Future<AuthStatus> restoreWorkSession() =>
    RustLib.instance.api.crateApiAuthRestoreWorkSession();

Future<List<SavedAccount>> listSavedAccounts() =>
    RustLib.instance.api.crateApiAuthListSavedAccounts();

Future<String?> activeAccountId() =>
    RustLib.instance.api.crateApiAuthActiveAccountId();

Future<AuthStatus> switchSavedAccount({required String accountId}) =>
    RustLib.instance.api.crateApiAuthSwitchSavedAccount(accountId: accountId);

Future<DeviceCode> beginWorkLogin() =>
    RustLib.instance.api.crateApiAuthBeginWorkLogin();

Future<AuthStatus> completeWorkLogin() =>
    RustLib.instance.api.crateApiAuthCompleteWorkLogin();

Future<void> cancelWorkLogin() =>
    RustLib.instance.api.crateApiAuthCancelWorkLogin();

Future<AuthStatus> logout() => RustLib.instance.api.crateApiAuthLogout();

class AuthStatus {
  final bool signedIn;
  final bool loginInProgress;

  const AuthStatus({required this.signedIn, required this.loginInProgress});

  @override
  int get hashCode => signedIn.hashCode ^ loginInProgress.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AuthStatus &&
          runtimeType == other.runtimeType &&
          signedIn == other.signedIn &&
          loginInProgress == other.loginInProgress;
}

class DeviceCode {
  final String verificationUri;
  final String userCode;
  final BigInt expiresInSeconds;

  const DeviceCode({
    required this.verificationUri,
    required this.userCode,
    required this.expiresInSeconds,
  });

  @override
  int get hashCode =>
      verificationUri.hashCode ^ userCode.hashCode ^ expiresInSeconds.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DeviceCode &&
          runtimeType == other.runtimeType &&
          verificationUri == other.verificationUri &&
          userCode == other.userCode &&
          expiresInSeconds == other.expiresInSeconds;
}

class SavedAccount {
  final String id;
  final String displayName;
  final String username;

  const SavedAccount({
    required this.id,
    required this.displayName,
    required this.username,
  });

  @override
  int get hashCode => id.hashCode ^ displayName.hashCode ^ username.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SavedAccount &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          displayName == other.displayName &&
          username == other.username;
}
