// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `convert_video_frame`, `ensure_camera_preview`, `ensure_microphone_preview`, `set_camera_device`, `stop_camera_preview`, `stop_microphone_preview`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ActiveIncomingCall`, `PendingIncomingCall`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`

Future<List<MediaDeviceInfo>> mediaDevices({required String kind}) =>
    RustLib.instance.api.crateApiCallsMediaDevices(kind: kind);

Future<int> previewMicrophonePeak() =>
    RustLib.instance.api.crateApiCallsPreviewMicrophonePeak();

Future<bool> previewSpeaker() =>
    RustLib.instance.api.crateApiCallsPreviewSpeaker();

Future<RemoteVideoFrame?> previewCameraFrame() =>
    RustLib.instance.api.crateApiCallsPreviewCameraFrame();

Future<RemoteVideoFrame?> remoteVideoFrame() =>
    RustLib.instance.api.crateApiCallsRemoteVideoFrame();

Future<RemoteVideoFrame?> localVideoFrame() =>
    RustLib.instance.api.crateApiCallsLocalVideoFrame();

Stream<CallEvent> listenCallEvents() =>
    RustLib.instance.api.crateApiCallsListenCallEvents();

Future<void> stopCallEvents() =>
    RustLib.instance.api.crateApiCallsStopCallEvents();

Future<void> startCall({required String conversationId}) =>
    RustLib.instance.api.crateApiCallsStartCall(conversationId: conversationId);

Future<void> hangUp() => RustLib.instance.api.crateApiCallsHangUp();

Future<void> acceptCall({required String callId}) =>
    RustLib.instance.api.crateApiCallsAcceptCall(callId: callId);

Future<void> declineCall({required String callId}) =>
    RustLib.instance.api.crateApiCallsDeclineCall(callId: callId);

class CallEvent {
  final String kind;
  final String callId;
  final String? conversationId;
  final String? displayName;
  final String? detail;

  const CallEvent({
    required this.kind,
    required this.callId,
    this.conversationId,
    this.displayName,
    this.detail,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      callId.hashCode ^
      conversationId.hashCode ^
      displayName.hashCode ^
      detail.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CallEvent &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          callId == other.callId &&
          conversationId == other.conversationId &&
          displayName == other.displayName &&
          detail == other.detail;
}

class MediaDeviceInfo {
  final String id;
  final String label;

  const MediaDeviceInfo({required this.id, required this.label});

  @override
  int get hashCode => id.hashCode ^ label.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MediaDeviceInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          label == other.label;
}

class RemoteVideoFrame {
  final int width;
  final int height;
  final Uint8List rgba;

  const RemoteVideoFrame({
    required this.width,
    required this.height,
    required this.rgba,
  });

  @override
  int get hashCode => width.hashCode ^ height.hashCode ^ rgba.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RemoteVideoFrame &&
          runtimeType == other.runtimeType &&
          width == other.width &&
          height == other.height &&
          rgba == other.rgba;
}
