// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `from`

Future<CustomReaction?> getCustomReaction({required String reactionType}) =>
    RustLib.instance.api.crateApiTeamsGetCustomReaction(
      reactionType: reactionType,
    );

Future<List<Team>> listTeams() => RustLib.instance.api.crateApiTeamsListTeams();

Future<List<Chat>> listChats({required BigInt limit}) =>
    RustLib.instance.api.crateApiTeamsListChats(limit: limit);

Future<List<UserPresence>> getPresences({required List<String> userIds}) =>
    RustLib.instance.api.crateApiTeamsGetPresences(userIds: userIds);

Future<UserDetails> getUserDetails({required String userId}) =>
    RustLib.instance.api.crateApiTeamsGetUserDetails(userId: userId);

Future<List<SavedAccountConversation>> listSavedAccountConversations({
  required String accountId,
  required BigInt limit,
}) => RustLib.instance.api.crateApiTeamsListSavedAccountConversations(
  accountId: accountId,
  limit: limit,
);

Future<SavedAccountNotification?> readSavedAccountNotification({
  required String accountId,
  required String conversationId,
  required BigInt messageLimit,
}) => RustLib.instance.api.crateApiTeamsReadSavedAccountNotification(
  accountId: accountId,
  conversationId: conversationId,
  messageLimit: messageLimit,
);

Future<List<Message>> readMessages({
  required String conversationId,
  required BigInt limit,
  required bool includeImages,
}) => RustLib.instance.api.crateApiTeamsReadMessages(
  conversationId: conversationId,
  limit: limit,
  includeImages: includeImages,
);

Future<void> sendMessage({
  required String conversationId,
  required String content,
}) => RustLib.instance.api.crateApiTeamsSendMessage(
  conversationId: conversationId,
  content: content,
);

Future<void> setReaction({
  required String conversationId,
  String? teamId,
  required String messageId,
  required String reactionType,
  required bool remove,
}) => RustLib.instance.api.crateApiTeamsSetReaction(
  conversationId: conversationId,
  teamId: teamId,
  messageId: messageId,
  reactionType: reactionType,
  remove: remove,
);

Future<UserProfile> getUserProfile() =>
    RustLib.instance.api.crateApiTeamsGetUserProfile();

Future<String?> getProfilePhoto({required String userId}) =>
    RustLib.instance.api.crateApiTeamsGetProfilePhoto(userId: userId);

Future<String?> getChatPhoto({required String chatId}) =>
    RustLib.instance.api.crateApiTeamsGetChatPhoto(chatId: chatId);

Future<String?> getTeamPhoto({required String teamId}) =>
    RustLib.instance.api.crateApiTeamsGetTeamPhoto(teamId: teamId);

Future<void> sendImageMessage({
  required String conversationId,
  String? teamId,
  required String caption,
  required String contentType,
  required String dataBase64,
}) => RustLib.instance.api.crateApiTeamsSendImageMessage(
  conversationId: conversationId,
  teamId: teamId,
  caption: caption,
  contentType: contentType,
  dataBase64: dataBase64,
);

Future<void> sendFileMessage({
  required String conversationId,
  String? teamId,
  required String fileName,
  required String contentType,
  required String dataBase64,
}) => RustLib.instance.api.crateApiTeamsSendFileMessage(
  conversationId: conversationId,
  teamId: teamId,
  fileName: fileName,
  contentType: contentType,
  dataBase64: dataBase64,
);

Future<List<Message>> readChannelMessages({
  required String teamId,
  required String channelId,
  required BigInt limit,
  required bool includeImages,
}) => RustLib.instance.api.crateApiTeamsReadChannelMessages(
  teamId: teamId,
  channelId: channelId,
  limit: limit,
  includeImages: includeImages,
);

Future<void> sendChannelMessage({
  required String teamId,
  required String channelId,
  required String content,
}) => RustLib.instance.api.crateApiTeamsSendChannelMessage(
  teamId: teamId,
  channelId: channelId,
  content: content,
);

Future<MessageImage?> loadMessageImage({required String url}) =>
    RustLib.instance.api.crateApiTeamsLoadMessageImage(url: url);

Future<String> reactionUserName({required String userId}) =>
    RustLib.instance.api.crateApiTeamsReactionUserName(userId: userId);

class Channel {
  final String id;
  final String name;

  const Channel({required this.id, required this.name});

  @override
  int get hashCode => id.hashCode ^ name.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Channel &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name;
}

class Chat {
  final String id;
  final String name;
  final bool isGroup;
  final String? profilePhotoUserId;
  final List<String> memberUserIds;
  final String? teamId;
  final String? lastMessageId;
  final String? lastMessagePreview;

  const Chat({
    required this.id,
    required this.name,
    required this.isGroup,
    this.profilePhotoUserId,
    required this.memberUserIds,
    this.teamId,
    this.lastMessageId,
    this.lastMessagePreview,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      isGroup.hashCode ^
      profilePhotoUserId.hashCode ^
      memberUserIds.hashCode ^
      teamId.hashCode ^
      lastMessageId.hashCode ^
      lastMessagePreview.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Chat &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          isGroup == other.isGroup &&
          profilePhotoUserId == other.profilePhotoUserId &&
          memberUserIds == other.memberUserIds &&
          teamId == other.teamId &&
          lastMessageId == other.lastMessageId &&
          lastMessagePreview == other.lastMessagePreview;
}

class CustomReaction {
  final String reactionType;
  final String shortcut;
  final String documentId;
  final String contentType;
  final String contentBase64;

  const CustomReaction({
    required this.reactionType,
    required this.shortcut,
    required this.documentId,
    required this.contentType,
    required this.contentBase64,
  });

  @override
  int get hashCode =>
      reactionType.hashCode ^
      shortcut.hashCode ^
      documentId.hashCode ^
      contentType.hashCode ^
      contentBase64.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CustomReaction &&
          runtimeType == other.runtimeType &&
          reactionType == other.reactionType &&
          shortcut == other.shortcut &&
          documentId == other.documentId &&
          contentType == other.contentType &&
          contentBase64 == other.contentBase64;
}

class Message {
  final String id;
  final String sender;
  final String? senderId;
  final bool isFromCurrentUser;
  final String timestamp;
  final String content;
  final List<MessageQuote> quotes;
  final List<MessageImage> images;
  final List<String> imageUrls;
  final List<Reaction> reactions;

  const Message({
    required this.id,
    required this.sender,
    this.senderId,
    required this.isFromCurrentUser,
    required this.timestamp,
    required this.content,
    required this.quotes,
    required this.images,
    required this.imageUrls,
    required this.reactions,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      sender.hashCode ^
      senderId.hashCode ^
      isFromCurrentUser.hashCode ^
      timestamp.hashCode ^
      content.hashCode ^
      quotes.hashCode ^
      images.hashCode ^
      imageUrls.hashCode ^
      reactions.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Message &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          sender == other.sender &&
          senderId == other.senderId &&
          isFromCurrentUser == other.isFromCurrentUser &&
          timestamp == other.timestamp &&
          content == other.content &&
          quotes == other.quotes &&
          images == other.images &&
          imageUrls == other.imageUrls &&
          reactions == other.reactions;
}

class MessageImage {
  final String? sourceUrl;
  final String contentType;
  final String dataBase64;

  const MessageImage({
    this.sourceUrl,
    required this.contentType,
    required this.dataBase64,
  });

  @override
  int get hashCode =>
      sourceUrl.hashCode ^ contentType.hashCode ^ dataBase64.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MessageImage &&
          runtimeType == other.runtimeType &&
          sourceUrl == other.sourceUrl &&
          contentType == other.contentType &&
          dataBase64 == other.dataBase64;
}

class MessageQuote {
  final String? messageId;
  final String sender;
  final String content;

  const MessageQuote({
    this.messageId,
    required this.sender,
    required this.content,
  });

  @override
  int get hashCode => messageId.hashCode ^ sender.hashCode ^ content.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MessageQuote &&
          runtimeType == other.runtimeType &&
          messageId == other.messageId &&
          sender == other.sender &&
          content == other.content;
}

class Reaction {
  final String reactionType;
  final BigInt count;
  final bool selected;
  final List<ReactionUser> users;

  const Reaction({
    required this.reactionType,
    required this.count,
    required this.selected,
    required this.users,
  });

  @override
  int get hashCode =>
      reactionType.hashCode ^
      count.hashCode ^
      selected.hashCode ^
      users.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Reaction &&
          runtimeType == other.runtimeType &&
          reactionType == other.reactionType &&
          count == other.count &&
          selected == other.selected &&
          users == other.users;
}

class ReactionUser {
  final String id;
  final String name;

  const ReactionUser({required this.id, required this.name});

  @override
  int get hashCode => id.hashCode ^ name.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReactionUser &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name;
}

class SavedAccountConversation {
  final String accountId;
  final String accountName;
  final String conversationId;
  final String conversationName;
  final bool isGroup;
  final bool isChannel;
  final String? lastMessageId;
  final String? lastMessagePreview;

  const SavedAccountConversation({
    required this.accountId,
    required this.accountName,
    required this.conversationId,
    required this.conversationName,
    required this.isGroup,
    required this.isChannel,
    this.lastMessageId,
    this.lastMessagePreview,
  });

  @override
  int get hashCode =>
      accountId.hashCode ^
      accountName.hashCode ^
      conversationId.hashCode ^
      conversationName.hashCode ^
      isGroup.hashCode ^
      isChannel.hashCode ^
      lastMessageId.hashCode ^
      lastMessagePreview.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SavedAccountConversation &&
          runtimeType == other.runtimeType &&
          accountId == other.accountId &&
          accountName == other.accountName &&
          conversationId == other.conversationId &&
          conversationName == other.conversationName &&
          isGroup == other.isGroup &&
          isChannel == other.isChannel &&
          lastMessageId == other.lastMessageId &&
          lastMessagePreview == other.lastMessagePreview;
}

class SavedAccountNotification {
  final String accountId;
  final String accountName;
  final String conversationId;
  final String conversationName;
  final bool isGroup;
  final bool isChannel;
  final Message message;
  final List<Message> messages;

  const SavedAccountNotification({
    required this.accountId,
    required this.accountName,
    required this.conversationId,
    required this.conversationName,
    required this.isGroup,
    required this.isChannel,
    required this.message,
    required this.messages,
  });

  @override
  int get hashCode =>
      accountId.hashCode ^
      accountName.hashCode ^
      conversationId.hashCode ^
      conversationName.hashCode ^
      isGroup.hashCode ^
      isChannel.hashCode ^
      message.hashCode ^
      messages.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SavedAccountNotification &&
          runtimeType == other.runtimeType &&
          accountId == other.accountId &&
          accountName == other.accountName &&
          conversationId == other.conversationId &&
          conversationName == other.conversationName &&
          isGroup == other.isGroup &&
          isChannel == other.isChannel &&
          message == other.message &&
          messages == other.messages;
}

class Team {
  final String id;
  final String name;
  final List<Channel> channels;

  const Team({required this.id, required this.name, required this.channels});

  @override
  int get hashCode => id.hashCode ^ name.hashCode ^ channels.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Team &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          channels == other.channels;
}

class UserDetails {
  final String userId;
  final String displayName;
  final String? email;
  final String? jobTitle;
  final String? availability;
  final String? activity;
  final String? statusMessage;

  const UserDetails({
    required this.userId,
    required this.displayName,
    this.email,
    this.jobTitle,
    this.availability,
    this.activity,
    this.statusMessage,
  });

  @override
  int get hashCode =>
      userId.hashCode ^
      displayName.hashCode ^
      email.hashCode ^
      jobTitle.hashCode ^
      availability.hashCode ^
      activity.hashCode ^
      statusMessage.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UserDetails &&
          runtimeType == other.runtimeType &&
          userId == other.userId &&
          displayName == other.displayName &&
          email == other.email &&
          jobTitle == other.jobTitle &&
          availability == other.availability &&
          activity == other.activity &&
          statusMessage == other.statusMessage;
}

class UserPresence {
  final String userId;
  final String availability;
  final String activity;

  const UserPresence({
    required this.userId,
    required this.availability,
    required this.activity,
  });

  @override
  int get hashCode =>
      userId.hashCode ^ availability.hashCode ^ activity.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UserPresence &&
          runtimeType == other.runtimeType &&
          userId == other.userId &&
          availability == other.availability &&
          activity == other.activity;
}

class UserProfile {
  final String? id;
  final String displayName;
  final String? email;

  const UserProfile({this.id, required this.displayName, this.email});

  @override
  int get hashCode => id.hashCode ^ displayName.hashCode ^ email.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UserProfile &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          displayName == other.displayName &&
          email == other.email;
}
