// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `listen_message_events_to`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`

Stream<MessageEvent> listenMessageEvents() =>
    RustLib.instance.api.crateApiTrouterListenMessageEvents();

Future<void> stopMessageEvents() =>
    RustLib.instance.api.crateApiTrouterStopMessageEvents();

class MessageEvent {
  final String conversationId;
  final String? accountId;
  final bool accountActive;
  final String resourceType;

  const MessageEvent({
    required this.conversationId,
    this.accountId,
    required this.accountActive,
    required this.resourceType,
  });

  @override
  int get hashCode =>
      conversationId.hashCode ^
      accountId.hashCode ^
      accountActive.hashCode ^
      resourceType.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MessageEvent &&
          runtimeType == other.runtimeType &&
          conversationId == other.conversationId &&
          accountId == other.accountId &&
          accountActive == other.accountActive &&
          resourceType == other.resourceType;
}
